module github.com/bridgeinpt/terraform-provider-bridgeport

go 1.25.0

// NOTE: go.sum is intentionally not committed in the initial scaffold because
// it must be generated by a Go toolchain. Run `go mod tidy` once (the Makefile
// `bootstrap` target does this) to resolve transitive deps and to add the
// BridgePort Go SDK (github.com/bridgeinpt/bridgeport/client) at the latest
// pseudo-version, then commit go.mod + go.sum.
require (
	github.com/hashicorp/terraform-plugin-framework v1.13.0
	github.com/hashicorp/terraform-plugin-go v0.25.0
	github.com/hashicorp/terraform-plugin-testing v1.11.0
)
